# Generated by Django 5.2.8 on 2025-11-27 19:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('summary', models.TextField(verbose_name='Resumen')),
                ('body', models.TextField(verbose_name='Cuerpo del Artículo')),
                ('image', models.ImageField(upload_to='news/images/', verbose_name='Imagen Principal')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('highlight_order', models.IntegerField(default=0, verbose_name='Orden de Destacado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-published_date', '-highlight_order'],
            },
        ),
    ]
