# Generated by Django 5.2.8 on 2025-11-28 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
            ],
            options={
                'verbose_name': 'Categoría (Plantel/Área)',
                'verbose_name_plural': 'Categorías (Planteles/Áreas)',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Posición')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('jersey_number', models.IntegerField(blank=True, null=True, verbose_name='Número de Camiseta')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='club/photos/', verbose_name='Foto')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo/Visible')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='club.category', verbose_name='Categoría')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.position', verbose_name='Posición/Rol')),
            ],
            options={
                'verbose_name': 'Persona (Jugador/Directivo)',
                'verbose_name_plural': 'Personas (Planteles/Áreas)',
                'ordering': ['category', 'order', 'full_name'],
            },
        ),
    ]
