# Generated by Django 5.2.8 on 2025-11-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['order', 'full_name'], 'verbose_name': 'Persona (Jugador/Directivo)', 'verbose_name_plural': 'Personas (Planteles/Áreas)'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='category',
        ),
        migrations.RemoveField(
            model_name='person',
            name='position',
        ),
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.ManyToManyField(related_name='people', to='club.category', verbose_name='Categorías (Planteles/Áreas)'),
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.ManyToManyField(related_name='people', to='club.position', verbose_name='Posiciones/Roles'),
        ),
    ]
