# Generated by Django 5.2.8 on 2025-11-28 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_person_options_remove_person_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['full_name'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='category',
        ),
        migrations.RemoveField(
            model_name='person',
            name='position',
        ),
        migrations.CreateModel(
            name='ClubRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Orden en la Categoría')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.category', verbose_name='Categoría (Equipo/Área)')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.person', verbose_name='Persona')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.position', verbose_name='Rol Específico')),
            ],
            options={
                'verbose_name': 'Rol de Club',
                'verbose_name_plural': 'Roles de Club',
                'ordering': ['category', 'order'],
                'unique_together': {('person', 'category', 'position')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(related_name='staff_members', through='club.ClubRole', to='club.category', verbose_name='Roles/Áreas Asignadas'),
        ),
    ]
